In [1]:
import main
import modifying_data
import pandas as pd
import json

# 하나의 경기 데이터 보여주기(크롤링한 상태와 변화된 상태)

In [2]:
# 10월 10일 kt 와 롯데 간의 첫번째 경기에 대한 데이터를 가져옵니다.
temp_data = main.get_data("20181010","KTLT1")

In [3]:
# 해당 경기 정보에 대해  제대로 데이터가 들어왔는지 확인합니다. 
temp_data['20181010_KTLT1']

{'scoreboard': [{'팀': 'KT',
   '승패': '승',
   '1': 1,
   '2': 4,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 4,
   '8': 1,
   '9': 0,
   '10': '-',
   '11': '-',
   '12': '-',
   'R': 10,
   'H': 12,
   'E': 0,
   'B': 3},
  {'팀': '롯데',
   '승패': '패',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 1,
   '9': 0,
   '10': '-',
   '11': '-',
   '12': '-',
   'R': 1,
   'H': 6,
   'E': 3,
   'B': 1}],
 'ETC_info': {'결승타': '유한준(1회 2사서 좌월 홈런)',
  '홈런': ['유한준20호(1회1점 박세웅', '강백호29호(8회1점 김건국', '한동희4호(8회1점 김사율)'],
  '2루타': ['황재균2(2 7회', '강백호(2회', '이진영(2회', '박경수(7회)'],
  '실책': ['채태인2(1회', '번즈(4회)'],
  '병살타': ['이진영(1회', '이대호(6회)'],
  '폭투': ['박세웅(1회', '정성종(7회', '윤성빈(9회)'],
  '심판': ['이계성', '권영철', '이용혁', '강광회'],
  '구장': '사직',
  '관중': '4,793',
  '개시': '14:59',
  '종료': '18:02',
  '경기시간': '3:03'},
 'away_batter': [{'포지션': '좌',
   '선수명': '강백호',
   '1': '1실',
   '2': '중2',
   '3': 0,
   '4': '삼진',
   '5': 0,
   '6': '2땅',
   '7': 0,
   '8': '우중홈',
   '9': 0,
   '타수': 5,
   '안타': 2,
   '타점': 3,
   '득점': 2,
   '타율': 0.294,
   '팀': 'KT'},
  {'포지션': '좌',
   '선수명': '송민섭',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': 0,
   '타수': 0,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.148,
   '팀': 'KT'},
  {'포지션': '지',
   '선수명': '이진영',
   '1': '2유병',
   '2': '좌중2',
   '3': 0,
   '4': '2실',
   '5': 0,
   '6': 0,
   '7': '중안',
   '8': 0,
   '9': 0,
   '타수': 4,
   '안타': 2,
   '타점': 1,
   '득점': 0,
   '타율': 0.31,
   '팀': 'KT'},
  {'포지션': '주지',
   '선수명': '김진곤',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': '2땅',
   '9': 0,
   '타수': 1,
   '안타': 0,
   '타점': 0,
   '득점': 1,
   '타율': 0.158,
   '팀': 'KT'},
  {'포지션': '우',
   '선수명': '유한준',
   '1': '좌홈',
   '2': '4구',
   '3': 0,
   '4': '유땅',
   '5': 0,
   '6': 0,
   '7': '투안',
   '8': 0,
   '9': 0,
   '타수': 3,
   '안타': 2,
   '타점': 1,
   '득점': 1,
   '타율': 0.337,
   '팀': 'KT'},
  {'포지션': '주우',
   '선수명': '배정대',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': '삼진',
   '9': 0,
   '타수': 1,
   '안타': 0,
   '타점': 0,
   '득점': 1,
   '타율': 0.2,
   '팀': 'KT'},
  {'포지션': '중',
   '선수명': '로하스',
   '1': '1실',
   '2': '2땅',
   '3': 0,
   '4': 0,
   '5': '4구',
   '6': 0,
   '7': '좌비',
   '8': '삼진',
   '9': 0,
   '타수': 4,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.304,
   '팀': 'KT'},
  {'포지션': '투',
   '선수명': '김사율',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': 0,
   '타수': 0,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.0,
   '팀': 'KT'},
  {'포지션': '투',
   '선수명': '고창성',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': 0,
   '타수': 0,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.0,
   '팀': 'KT'},
  {'포지션': '二',
   '선수명': '박경수',
   '1': '삼진',
   '2': '우비',
   '3': 0,
   '4': 0,
   '5': '삼진',
   '6': 0,
   '7': '좌2',
   '8': 0,
   '9': 0,
   '타수': 4,
   '안타': 1,
   '타점': 1,
   '득점': 0,
   '타율': 0.265,
   '팀': 'KT'},
  {'포지션': '주二',
   '선수명': '박기혁',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': '4구',
   '타수': 0,
   '안타': 0,
   '타점': 0,
   '득점': 1,
   '타율': 0.215,
   '팀': 'KT'},
  {'포지션': '三',
   '선수명': '황재균',
   '1': 0,
   '2': '좌2',
   '3': '2땅',
   '4': 0,
   '5': '2땅',
   '6': 0,
   '7': '중2',
   '8': 0,
   '9': '중비',
   '타수': 5,
   '안타': 2,
   '타점': 1,
   '득점': 2,
   '타율': 0.291,
   '팀': 'KT'},
  {'포지션': '三',
   '선수명': '고명성',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': 0,
   '타수': 0,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.0,
   '팀': 'KT'},
  {'포지션': '一',
   '선수명': '오태곤',
   '1': 0,
   '2': '우안',
   '3': '중비',
   '4': 0,
   '5': '삼진',
   '6': 0,
   '7': '투땅',
   '8': 0,
   '9': '삼진',
   '타수': 5,
   '안타': 1,
   '타점': 0,
   '득점': 0,
   '타율': 0.261,
   '팀': 'KT'},
  {'포지션': '포',
   '선수명': '장성우',
   '1': 0,
   '2': '우안',
   '3': '우비',
   '4': 0,
   '5': 0,
   '6': '우비',
   '7': '중안',
   '8': 0,
   '9': 0,
   '타수': 4,
   '안타': 2,
   '타점': 2,
   '득점': 1,
   '타율': 0.261,
   '팀': 'KT'},
  {'포지션': '포',
   '선수명': '이해창',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': '3파',
   '타수': 1,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.216,
   '팀': 'KT'},
  {'포지션': '유',
   '선수명': '심우준',
   '1': 0,
   '2': '투땅',
   '3': 0,
   '4': '중비',
   '5': 0,
   '6': '중비',
   '7': '2비',
   '8': 0,
   '9': 0,
   '타수': 4,
   '안타': 0,
   '타점': 0,
   '득점': 1,
   '타율': 0.258,
   '팀': 'KT'}],
 'home_batter': [{'포지션': '중',
   '선수명': '민병헌',
   '1': '삼진',
   '2': 0,
   '3': '중비',
   '4': 0,
   '5': 0,
   '6': '삼진',
   '7': 0,
   '8': 0,
   '9': 0,
   '타수': 3,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.316,
   '팀': '롯데'},
  {'포지션': '중',
   '선수명': '나경민',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': '삼진',
   '9': 0,
   '타수': 1,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.264,
   '팀': '롯데'},
  {'포지션': '우',
   '선수명': '손아섭',
   '1': '투땅',
   '2': 0,
   '3': 0,
   '4': '중비',
   '5': 0,
   '6': '좌안',
   '7': 0,
   '8': 0,
   '9': 0,
   '타수': 3,
   '안타': 1,
   '타점': 0,
   '득점': 0,
   '타율': 0.337,
   '팀': '롯데'},
  {'포지션': '우',
   '선수명': '조홍석',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': '2직',
   '9': 0,
   '타수': 1,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.22,
   '팀': '롯데'},
  {'포지션': '좌',
   '선수명': '전준우',
   '1': '3땅',
   '2': 0,
   '3': 0,
   '4': '3안',
   '5': 0,
   '6': '중안',
   '7': 0,
   '8': 0,
   '9': 0,
   '타수': 3,
   '안타': 2,
   '타점': 0,
   '득점': 0,
   '타율': 0.343,
   '팀': '롯데'},
  {'포지션': '一',
   '선수명': '나원탁',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': '우비',
   '타수': 1,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.13,
   '팀': '롯데'},
  {'포지션': '지',
   '선수명': '이대호',
   '1': 0,
   '2': '2비',
   '3': 0,
   '4': '삼진',
   '5': 0,
   '6': '유2병',
   '7': 0,
   '8': 0,
   '9': '삼진',
   '타수': 4,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.338,
   '팀': '롯데'},
  {'포지션': '一',
   '선수명': '채태인',
   '1': 0,
   '2': '우안',
   '3': 0,
   '4': '우비',
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': 0,
   '타수': 2,
   '안타': 1,
   '타점': 0,
   '득점': 0,
   '타율': 0.296,
   '팀': '롯데'},
  {'포지션': '포',
   '선수명': '나종덕',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': '3땅',
   '8': 0,
   '9': '4구',
   '타수': 1,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.121,
   '팀': '롯데'},
  {'포지션': '유',
   '선수명': '문규현',
   '1': 0,
   '2': '우비',
   '3': 0,
   '4': 0,
   '5': '삼진',
   '6': 0,
   '7': 0,
   '8': 0,
   '9': 0,
   '타수': 2,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.282,
   '팀': '롯데'},
  {'포지션': '一좌',
   '선수명': '김문호',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': '삼진',
   '8': 0,
   '9': '3비',
   '타수': 2,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.25,
   '팀': '롯데'},
  {'포지션': '三二',
   '선수명': '전병우',
   '1': 0,
   '2': '삼진',
   '3': 0,
   '4': 0,
   '5': '삼진',
   '6': 0,
   '7': '삼진',
   '8': 0,
   '9': 0,
   '타수': 3,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.388,
   '팀': '롯데'},
  {'포지션': '二',
   '선수명': '번즈',
   '1': 0,
   '2': 0,
   '3': '삼진',
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': 0,
   '타수': 1,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.271,
   '팀': '롯데'},
  {'포지션': '二',
   '선수명': '신본기',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': '2비',
   '6': 0,
   '7': 0,
   '8': 0,
   '9': 0,
   '타수': 1,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.294,
   '팀': '롯데'},
  {'포지션': '三',
   '선수명': '한동희',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': '우중홈',
   '9': 0,
   '타수': 1,
   '안타': 1,
   '타점': 1,
   '득점': 1,
   '타율': 0.229,
   '팀': '롯데'},
  {'포지션': '포',
   '선수명': '안중열',
   '1': 0,
   '2': 0,
   '3': '3땅',
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': 0,
   '타수': 1,
   '안타': 0,
   '타점': 0,
   '득점': 0,
   '타율': 0.252,
   '팀': '롯데'},
  {'포지션': '타一',
   '선수명': '정훈',
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': '우안',
   '7': 0,
   '8': '삼진',
   '9': 0,
   '타수': 2,
   '안타': 1,
   '타점': 0,
   '득점': 0,
   '타율': 0.304,
   '팀': '롯데'}],
 'away_pitcher': [{'선수명': '고영표',
   '등판': '선발',
   '결과': '승',
   '승': 6,
   '패': 9,
   '세': 0,
   '이닝': '5',
   '타자': 17,
   '투구수': 65,
   '타수': 17,
   '피안타': 2,
   '홈런': 0.0,
   '4사구': 0.0,
   '삼진': 6.0,
   '실점': 0.0,
   '자책': 0.0,
   '평균자책점': 5.13,
   '팀': 'KT'},
  {'선수명': '김태오',
   '등판': '6.9',
   '결과': 0,
   '승': 1,
   '패': 2,
   '세': 0,
   '이닝': '1\\/3',
   '타자': 4,
   '투구수': 14,
   '타수': 4,
   '피안타': 3,
   '홈런': 0.0,
   '4사구': 0.0,
   '삼진': 1.0,
   '실점': 0.0,
   '자책': 0.0,
   '평균자책점': 5.95,
   '팀': 'KT'},
  {'선수명': '엄상백',
   '등판': '6.4',
   '결과': '홀드',
   '승': 1,
   '패': 8,
   '세': 2,
   '이닝': '2\\/3',
   '타자': 1,
   '투구수': 6,
   '타수': 1,
   '피안타': 0,
   '홈런': 0.0,
   '4사구': 0.0,
   '삼진': 0.0,
   '실점': 0.0,
   '자책': 0.0,
   '평균자책점': 5.48,
   '팀': 'KT'},
  {'선수명': '이종혁',
   '등판': '7.5',
   '결과': 0,
   '승': 0,
   '패': 5,
   '세': 1,
   '이닝': '1',
   '타자': 3,
   '투구수': 11,
   '타수': 3,
   '피안타': 0,
   '홈런': 0.0,
   '4사구': 0.0,
   '삼진': 2.0,
   '실점': 0.0,
   '자책': 0.0,
   '평균자책점': 4.5,
   '팀': 'KT'},
  {'선수명': '김사율',
   '등판': '8.8',
   '결과': 0,
   '승': 1,
   '패': 2,
   '세': 0,
   '이닝': '1',
   '타자': 4,
   '투구수': 21,
   '타수': 4,
   '피안타': 1,
   '홈런': 1.0,
   '4사구': 0.0,
   '삼진': 2.0,
   '실점': 1.0,
   '자책': 1.0,
   '평균자책점': 5.8,
   '팀': 'KT'},
  {'선수명': '고창성',
   '등판': '9.3',
   '결과': 0,
   '승': 2,
   '패': 0,
   '세': 0,
   '이닝': '1',
   '타자': 4,
   '투구수': 16,
   '타수': 3,
   '피안타': 0,
   '홈런': 0.0,
   '4사구': 1.0,
   '삼진': 1.0,
   '실점': 0.0,
   '자책': 0.0,
   '평균자책점': 6.69,
   '팀': 'KT'}],
 'home_pitcher': [{'선수명': '박세웅',
   '등판': '선발',
   '결과': '패',
   '승': 1,
   '패': 5,
   '세': 0,
   '이닝': '1 1\\/3',
   '타자': 12,
   '투구수': 36,
   '타수': 11,
   '피안타': 6,
   '홈런': 1.0,
   '4사구': 1.0,
   '삼진': 1.0,
   '실점': 5.0,
   '자책': 5.0,
   '평균자책점': 9.92,
   '팀': '롯데'},
  {'선수명': '정성종',
   '등판': '2.4',
   '결과': 0,
   '승': 0,
   '패': 0,
   '세': 0,
   '이닝': '5',
   '타자': 20,
   '투구수': 77,
   '타수': 19,
   '피안타': 3,
   '홈런': 0.0,
   '4사구': 1.0,
   '삼진': 3.0,
   '실점': 3.0,
   '자책': 3.0,
   '평균자책점': 4.86,
   '팀': '롯데'},
  {'선수명': '김건국',
   '등판': '7.6',
   '결과': 0,
   '승': 0,
   '패': 0,
   '세': 0,
   '이닝': '1 1\\/3',
   '타자': 7,
   '투구수': 37,
   '타수': 7,
   '피안타': 3,
   '홈런': 1.0,
   '4사구': 0.0,
   '삼진': 1.0,
   '실점': 2.0,
   '자책': 2.0,
   '평균자책점': 3.18,
   '팀': '롯데'},
  {'선수명': '윤성빈',
   '등판': '8.4',
   '결과': 0,
   '승': 2,
   '패': 5,
   '세': 0,
   '이닝': '1 1\\/3',
   '타자': 5,
   '투구수': 20,
   '타수': 4,
   '피안타': 0,
   '홈런': 0.0,
   '4사구': 1.0,
   '삼진': 2.0,
   '실점': 0.0,
   '자책': 0.0,
   '평균자책점': 6.43,
   '팀': '롯데'}]}

In [19]:
# 어떤 테이블이 있는지 key 값을 통해 확인합니다. 
list(temp_data['20181010_KTLT1'].keys())

['scoreboard',
 'ETC_info',
 'away_batter',
 'home_batter',
 'away_pitcher',
 'home_pitcher']

In [20]:
#경기의 점수 상황 판을 테이블로 확인합니다.
pd.DataFrame(temp_data['20181010_KTLT1']['scoreboard'])

   1 10 11 12  2  3  4  5  6  7  8  9  B  E   H   R 승패   팀
0  1  -  -  -  4  0  0  0  0  4  1  0  3  0  12  10  승  KT
1  0  -  -  -  0  0  0  0  0  0  1  0  1  3   6   1  패  롯데

In [21]:
# 도루를 비롯한 구장, 관중 수 등의 정보를 확인합니다.
temp_data['20181010_KTLT1']['ETC_info']

{'결승타': '유한준(1회 2사서 좌월 홈런)',
 '홈런': ['유한준20호(1회1점 박세웅', '강백호29호(8회1점 김건국', '한동희4호(8회1점 김사율)'],
 '2루타': ['황재균2(2 7회', '강백호(2회', '이진영(2회', '박경수(7회)'],
 '실책': ['채태인2(1회', '번즈(4회)'],
 '병살타': ['이진영(1회', '이대호(6회)'],
 '폭투': ['박세웅(1회', '정성종(7회', '윤성빈(9회)'],
 '심판': ['이계성', '권영철', '이용혁', '강광회'],
 '구장': '사직',
 '관중': '4,793',
 '개시': '14:59',
 '종료': '18:02',
 '경기시간': '3:03'}

In [22]:
# 원정팀인 kt의 타자 정보를 테이블로 확인합니다.
pd.DataFrame(temp_data['20181010_KTLT1']['away_batter']).head()

     1    2  3   4  5   6   7    8  9  득점  선수명  안타  타수     타율  타점   팀 포지션
0   1실   중2  0  삼진  0  2땅   0  우중홈  0   2  강백호   2   5  0.294   3  KT   좌
1    0    0  0   0  0   0   0    0  0   0  송민섭   0   0  0.148   0  KT   좌
2  2유병  좌중2  0  2실  0   0  중안    0  0   0  이진영   2   4  0.310   1  KT   지
3    0    0  0   0  0   0   0   2땅  0   1  김진곤   0   1  0.158   0  KT  주지
4   좌홈   4구  0  유땅  0   0  투안    0  0   1  유한준   2   3  0.337   1  KT   우

In [23]:
# 홈팀인 롯데의 타자 정보를 테이블로 확인합니다.
pd.DataFrame(temp_data['20181010_KTLT1']['home_batter']).head()

    1  2   3   4  5   6  7   8  9  득점  선수명  안타  타수     타율  타점   팀 포지션
0  삼진  0  중비   0  0  삼진  0   0  0   0  민병헌   0   3  0.316   0  롯데   중
1   0  0   0   0  0   0  0  삼진  0   0  나경민   0   1  0.264   0  롯데   중
2  투땅  0   0  중비  0  좌안  0   0  0   0  손아섭   1   3  0.337   0  롯데   우
3   0  0   0   0  0   0  0  2직  0   0  조홍석   0   1  0.220   0  롯데   우
4  3땅  0   0  3안  0  중안  0   0  0   0  전준우   2   3  0.343   0  롯데   좌

In [24]:
#원정팀인 kt의 투수 정보를 테이블로 확인합니다.
pd.DataFrame(temp_data['20181010_KTLT1']['away_pitcher'])

,4사구,결과,등판,삼진,선수명,세,승,실점,이닝,자책,타수,타자,투구수,팀,패,평균자책점,피안타,홈런
0,0.0,승,선발,6.0,고영표,0,6,0.0,5,0.0,17,17,65,KT,9,5.13,2,0.0
1,0.0,0,6.9,1.0,김태오,0,1,0.0,1\/3,0.0,4,4,14,KT,2,5.95,3,0.0
2,0.0,홀드,6.4,0.0,엄상백,2,1,0.0,2\/3,0.0,1,1,6,KT,8,5.48,0,0.0
3,0.0,0,7.5,2.0,이종혁,1,0,0.0,1,0.0,3,3,11,KT,5,4.50,0,0.0
4,0.0,0,8.8,2.0,김사율,0,1,1.0,1,1.0,4,4,21,KT,2,5.80,1,1.0
5,1.0,0,9.3,1.0,고창성,0,2,0.0,1,0.0,3,4,16,KT,0,6.69,0,0.0

In [25]:
# 홈팀인 롯데의 투수 정보를 테이블로 확인합니다.
pd.DataFrame(temp_data['20181010_KTLT1']['home_pitcher'])

,4사구,결과,등판,삼진,선수명,세,승,실점,이닝,자책,타수,타자,투구수,팀,패,평균자책점,피안타,홈런
0,1.0,패,선발,1.0,박세웅,0,1,5.0,1 1\/3,5.0,11,12,36,롯데,5,9.92,6,1.0
1,1.0,0,2.4,3.0,정성종,0,0,3.0,5,3.0,19,20,77,롯데,0,4.86,3,0.0
2,0.0,0,7.6,1.0,김건국,0,0,2.0,1 1\/3,2.0,7,7,37,롯데,0,3.18,3,1.0
3,1.0,0,8.4,2.0,윤성빈,0,2,0.0,1 1\/3,0.0,4,5,20,롯데,5,6.43,0,0.0

In [3]:
#타자와 투수데이터를 다루기 편하게 변경해 줍니다.
temp=main.modify_data(temp_data)

In [27]:
#원정팀의 타자 데이터가 제대로 변경됬는지 확인합니다.
pd.DataFrame(temp['20181010_KTLT1']['away_batter']).head()

,1,2,3,4,5,6,7,8,9,경기날짜,...,득점,선수명,안타,원정팀,타수,타율,타점,팀,포지션,홈팀
0,6000,1118,0,2000,0,7101,0,1300,0,2018-10-10,...,2,강백호,2,KT,5,0.294,3,KT,좌,롯데
1,0,0,0,0,0,0,0,0,0,2018-10-10,...,0,송민섭,0,KT,0,0.148,0,KT,좌,롯데
2,7206,1117,0,6001,0,0,1019,0,0,2018-10-10,...,0,이진영,2,KT,4,0.310,1,KT,지,롯데
3,0,0,0,0,0,0,0,7101,0,2018-10-10,...,1,김진곤,0,KT,1,0.158,0,KT,주지,롯데
4,1303,3000,0,7104,0,0,1023,0,0,2018-10-10,...,1,유한준,2,KT,3,0.337,1,KT,우,롯데

In [28]:
#홈팀의 타자 데이터가 제대로 변경됬는지 확인합니다.
pd.DataFrame(temp['20181010_KTLT1']['home_batter']).head()

,1,2,3,4,5,6,7,8,9,경기날짜,...,득점,선수명,안타,원정팀,타수,타율,타점,팀,포지션,홈팀
0,2000,0,7006,0,0,2000,0,0,0,2018-10-10,...,0,민병헌,0,KT,3,0.316,0,롯데,중,롯데
1,0,0,0,0,0,0,0,2000,0,2018-10-10,...,0,나경민,0,KT,1,0.264,0,롯데,중,롯데
2,7107,0,0,7006,0,1017,0,0,0,2018-10-10,...,0,손아섭,1,KT,3,0.337,0,롯데,우,롯데
3,0,0,0,0,0,0,0,7301,0,2018-10-10,...,0,조홍석,0,KT,1,0.220,0,롯데,우,롯데
4,7102,0,0,1008,0,1019,0,0,0,2018-10-10,...,0,전준우,2,KT,3,0.343,0,롯데,좌,롯데

In [4]:
#원정팀의 투수 데이터가 제대로 변경됬는지 확인합니다.
pd.DataFrame(temp['20181010_KTLT1']['away_pitcher']).head()

,4사구,inning,restinning,경기날짜,더블헤더여부,등판,무승부,삼진,선수명,세이브,...,원정팀,자책,타수,타자,투구수,팀,패배,포지션,홀드,홈팀
0,0.0,5,0,2018-10-10,1,1.1,0,6.0,고영표,0,...,KT,0.0,17,17,65,KT,0,선발투수,0,롯데
1,0.0,0,1,2018-10-10,1,6.9,0,1.0,김태오,0,...,KT,0.0,4,4,14,KT,0,불펜투수,0,롯데
2,0.0,0,2,2018-10-10,1,6.4,0,0.0,엄상백,0,...,KT,0.0,1,1,6,KT,0,불펜투수,1,롯데
3,0.0,1,0,2018-10-10,1,7.5,0,2.0,이종혁,0,...,KT,0.0,3,3,11,KT,0,불펜투수,0,롯데
4,0.0,1,0,2018-10-10,1,8.8,0,2.0,김사율,0,...,KT,1.0,4,4,21,KT,0,불펜투수,0,롯데

In [5]:
#홈팀의 투수 데이터가 제대로 변경됬는지 확인합니다.
pd.DataFrame(temp['20181010_KTLT1']['home_pitcher']).head()

,4사구,inning,restinning,경기날짜,더블헤더여부,등판,무승부,삼진,선수명,세이브,...,원정팀,자책,타수,타자,투구수,팀,패배,포지션,홀드,홈팀
0,1.0,1,1,2018-10-10,1,1.1,0,1.0,박세웅,0,...,KT,5.0,11,12,36,롯데,1,선발투수,0,롯데
1,1.0,5,0,2018-10-10,1,2.4,0,3.0,정성종,0,...,KT,3.0,19,20,77,롯데,0,불펜투수,0,롯데
2,0.0,1,1,2018-10-10,1,7.6,0,1.0,김건국,0,...,KT,2.0,7,7,37,롯데,0,불펜투수,0,롯데
3,1.0,1,1,2018-10-10,1,8.4,0,2.0,윤성빈,0,...,KT,0.0,4,5,20,롯데,0,불펜투수,0,롯데

# 한화 2018시즌 경기자료 데이터로 구성하기

In [8]:
#전체 자료를 수집하는 방법
kbo_id_full=pd.read_csv("./data/KBO_gameid_full.csv")
kbo_id_full.date=kbo_id_full.date.astype(str)

In [ ]:
# 주의! for문이 다 돌아가는데 오랜 시간이 걸립니다.
# 전체 자료를 저장한 json 파일이 따로 있으니 코드를 작동시키지 않고 그것을 이용하셔도 됩니다.
full_data={}
for i in range(0,len(kbo_id_full)):
    temp_data = main.get_data(kbo_id_full.date[i],kbo_id_full.gameid[i])
    temp_data = main.modify_data(temp_data)
    full_data.update(temp_data)

In [15]:
#전체자료가 다 들어왔는지 확인해줍니다.
len(full_data)

5628

In [6]:
#한화의 경기 아이디 목록을 불러와 줍니다.
sample=pd.read_csv("./data/Hanhwa_game_id_sample.csv")
sample.date=sample.date.astype(str)

In [7]:
# 각 경기별로 자료를 get하고 변형해 딕트로 모아줍니다.
temp_full ={}
for i in range(0,len(sample)):
    temp_data = main.get_data(sample.date[i],sample.gameid[i])
    temp_data = main.modify_data(temp_data)
    temp_full.update(temp_data)

In [8]:
# 144경기가 다 들어왔는지 확인합니다. 
len(temp_full.keys())

144

In [27]:
#첫 번째 경기를 잡아서 데이터가 잘 변경 됬는지 확인합니다.
#위에서 한 것과 똑같이 스코어 보드부터 홈,원정 타자 투수 정보까지 확인해줍니다.
pd.DataFrame(temp_full[list(temp_full.keys())[0]]['scoreboard'])

   1 10 11 12  2  3  4  5  6  7  8  9  B  E   H  R 승패   팀
0  1  -  -  -  1  0  0  0  0  1  0  0  1  1  13  3  패  한화
1  0  -  -  -  0  1  3  2  0  0  0  -  4  1  12  6  승  넥센

In [28]:
# 원정팀 타자 데이터가 잘 변경되었는지 확인해 줍니다.
pd.DataFrame(temp_full[list(temp_full.keys())[0]]['away_batter']).head()

,1,2,3,4,5,6,7,8,9,경기날짜,...,득점,선수명,안타,원정팀,타수,타율,타점,팀,포지션,홈팀
0,2000,7003,0,0,7405,0,1019,0,2000,2018-03-24,...,0,이용규,1,한화,5,0.20,1,한화,중,넥센
1,7006,0,7107,0,1017,0,7002,0,7101,2018-03-24,...,0,양성우,1,한화,5,0.20,0,한화,좌,넥센
2,1017,0,1019,0,0,2000,0,7003,0,2018-03-24,...,1,송광민,2,한화,4,0.50,0,한화,一,넥센
3,1011,0,1017,0,0,2000,0,1017,0,2018-03-24,...,0,김태균,3,한화,4,0.75,0,한화,지,넥센
4,0,0,0,0,0,0,0,0,0,2018-03-24,...,0,이동훈,0,한화,0,0.00,0,한화,주,넥센

In [31]:
#  홈팀 타자 데이터가 잘 변경되었는지 확인해 줍니다.
pd.DataFrame(temp_full[list(temp_full.keys())[0]]['home_batter']).head()

,1,2,3,4,5,6,7,8,9,경기날짜,...,득점,선수명,안타,원정팀,타수,타율,타점,팀,포지션,홈팀
0,7101,0,7100,1011,2000,0,7101,0,0.0,2018-03-24,...,0,서건창,1,한화,5,0.2,0,넥센,二,넥센
1,0,0,0,0,0,0,0,0,0.0,2018-03-24,...,0,김지수,0,한화,0,0.0,0,넥센,二,넥센
2,2000,0,2000,2000,7005,0,7003,0,0.0,2018-03-24,...,0,초이스,0,한화,5,0.0,0,넥센,우,넥센
3,2000,0,1302,3000,0,1011,0,7102,0.0,2018-03-24,...,1,김태완,2,한화,4,0.5,1,넥센,지,넥센
4,0,2000,1017,6002,0,1017,0,7302,0.0,2018-03-24,...,0,박병호,2,한화,5,0.4,0,넥센,一,넥센

In [32]:
#원정팀  투수 데이터가 잘 변경되었는지 확인 합니다.
pd.DataFrame(temp_full[list(temp_full.keys())[0]]['away_pitcher']).head()

,4사구,inning,restinning,경기날짜,더블헤더여부,등판,무승부,삼진,선수명,세이브,...,실점,원정팀,자책,타수,타자,팀,패배,포지션,홀드,홈팀
0,4.0,4,0,2018-03-24,0,1.1,0,8.0,샘슨,0,...,6.0,한화,5.0,21,25,한화,1,선발투수,0,넥센
1,0.0,0,2,2018-03-24,0,5.8,0,1.0,김범수,0,...,0.0,한화,0.0,3,3,한화,0,불펜투수,0,넥센
2,0.0,0,2,2018-03-24,0,5.2,0,0.0,심수창,0,...,0.0,한화,0.0,4,4,한화,0,불펜투수,0,넥센
3,0.0,0,2,2018-03-24,0,6.6,0,0.0,박주홍,0,...,0.0,한화,0.0,2,2,한화,0,불펜투수,0,넥센
4,0.0,0,2,2018-03-24,0,7.8,0,0.0,송은범,0,...,0.0,한화,0.0,3,3,한화,0,불펜투수,0,넥센

In [33]:
#홈팀  투수 데이터가 잘 변경되었는지 확인 합니다.
pd.DataFrame(temp_full[list(temp_full.keys())[0]]['home_pitcher']).head()

,4사구,inning,restinning,경기날짜,더블헤더여부,등판,무승부,삼진,선수명,세이브,...,실점,원정팀,자책,타수,타자,팀,패배,포지션,홀드,홈팀
0,1.0,6,2,2018-03-24,0,1.1,0,6.0,로저스,0,...,3.0,한화,2.0,26,27,넥센,0,선발투수,0,넥센
1,0.0,0,1,2018-03-24,0,7.1,0,0.0,이보근,0,...,0.0,한화,0.0,2,2,넥센,0,불펜투수,1,넥센
2,0.0,1,0,2018-03-24,0,8.3,0,1.0,김상수,0,...,0.0,한화,0.0,4,4,넥센,0,불펜투수,1,넥센
3,0.0,1,0,2018-03-24,0,9.7,0,2.0,조상우,1,...,0.0,한화,0.0,5,5,넥센,0,불펜투수,0,넥센

In [9]:
#1년치 한화 경기를 json 파일로 저장해 줍니다.
temp_file_name = "./sample/Hanhwa_normalseason_2018.json"

with open(temp_file_name, 'w') as outfile:  
    json.dump(temp_full, outfile)

In [11]:
#전체 자료를 json파일로 저장합니다. 
temp_file_name = "./data/KBO_normalseason_full.json"

with open(temp_file_name, 'w') as outfile:  
    json.dump(full_data, outfile)

# 1년치 경기 자료를 가지고 한화 선수들의 타율이나 팀타율 구해보기

In [10]:
#위에서 저장한 json파일여는 방법입니다.
temp_file_name = "./sample/Hanhwa_normalseason_2018.json"
with open(temp_file_name) as outfile:  
    hanhwa_data=json.load(outfile)

In [3]:
# 위의 과정을 따라왔다면 json 파일을 새로 열지 않은 상태에서 진행해도 무방합니다.
#경기별로 홈팀과 원정팀의 타자데이터만 모아줍니다.
away_team = pd.DataFrame()
home_team = pd.DataFrame()
for i in hanhwa_data.keys():
    away_team = away_team.append(pd.DataFrame(hanhwa_data[i]['away_batter']),sort=True)
    home_team = home_team.append(pd.DataFrame(hanhwa_data[i]['home_batter']),sort=True)

In [4]:
# 홈과 원정으로 분리되어 저장한 타자 기록들을 하나로 모아줍니다.
hanhwa_2018_all=pd.concat([away_team,home_team],ignore_index=True)
hanhwa_2018_all=hanhwa_2018_all.fillna(0)

In [5]:
# 열순서를 조정해 줍니다
hanhwa_batter=pd.DataFrame(hanhwa_2018_all,
                           columns=['경기날짜','선수명','포지션','팀',"더블헤더여부",'홈팀','원정팀','1','2','3','4','5','6','7','8','9','10','11','12','안타','타수','타율','타점','득점'])

In [6]:
# 만든 데이터를 csv파일로 저장해 줍니다.
hanhwa_batter.to_csv("./sample/Hanhwa_batter_data_2018.csv")

In [11]:
#같은 방식으로 투수 데이터도 모아줍니다.
away_team = pd.DataFrame()
home_team = pd.DataFrame()
for i in hanhwa_data.keys():
    away_team = away_team.append(pd.DataFrame(hanhwa_data[i]['away_pitcher']),sort=True)
    home_team = home_team.append(pd.DataFrame(hanhwa_data[i]['home_pitcher']),sort=True)

In [12]:
#원정팀과 홈팀의 투수자료를 하나로 모아줍니다.
hanhwa_2018_all=pd.concat([away_team,home_team],ignore_index=True)
hanhwa_2018_all=hanhwa_2018_all.fillna(0)

In [13]:
#열 순서를 재정리 해줍니다.
hanhwa_pitcher=pd.DataFrame(hanhwa_2018_all,
                            columns=['경기날짜','선수명','포지션','팀','더블헤더여부','홈팀','원정팀','등판', 'inning', 'restinning', '승리','패배','무승부','세이브','홀드','삼진','4사구','실점','자책','투구수', '타수', '타자'])

In [15]:
# 만든 데이터를 csv파일로 저장해 줍니다.
hanhwa_pitcher.to_csv("./sample/Hanhwa_pitcher_data_2018.csv")

In [11]:
# 한화의 팀타율을 구해봅니다.
sum(hanhwa_batter[hanhwa_batter['팀'] == "한화"]['안타'])/sum(hanhwa_batter[hanhwa_batter['팀'] == "한화"]['타수'])

0.2753419147224457

In [12]:
# 이용규 선수 개인의 타율 구해봅니다.
h=sum(hanhwa_batter[(hanhwa_batter['팀'] == "한화") & (hanhwa_batter['선수명']=="이용규")]['안타'])
ab=sum(hanhwa_batter[(hanhwa_batter['팀'] == "한화")&(hanhwa_batter['선수명']=="이용규")]['타수'])
h/ab

0.29327902240325865

In [16]:
#한화의 팀 방어율을 구해봅니다. 
#먼저 팀의 총 자책점에 9를 곱한 변환값을 구해줍니다.
er=sum(hanhwa_pitcher[hanhwa_pitcher['팀'] == "한화"]['자책'])*9
er

6309.0

In [17]:
#팀의 총 이닝을 계산합니다.
ip=(sum(hanhwa_pitcher[hanhwa_pitcher['팀'] == "한화"]['inning'].astype(int))+
    sum(hanhwa_pitcher[hanhwa_pitcher['팀'] == "한화"]['restinning'].astype(int))/3)
ip

1274.0

In [18]:
#위에서 구한 것을 이용해 방어율을 계산합니다.
er/ip

4.952119309262167

In [19]:
# 정우람 선수의 방어율을 구해봅니다.
#먼저 자책점 변환값을 구해줍니다.
er=sum(hanhwa_pitcher[(hanhwa_pitcher['팀'] == "한화")&(hanhwa_pitcher['선수명'] == "정우람")]['자책'])*9
er

180.0

In [20]:
#정우람 선수의 총 이닝수를 구해줍니다.
ip=(sum(hanhwa_pitcher[(hanhwa_pitcher['팀'] == "한화")&(hanhwa_pitcher['선수명'] == "정우람")]['inning'].astype(int))+
    sum(hanhwa_pitcher[(hanhwa_pitcher['팀'] == "한화")&(hanhwa_pitcher['선수명'] == "정우람")]['restinning'].astype(int))/3)

In [21]:
#최종적으로 두 가지를 이용해 정우람 선수의 방어율을 구합니다.
er/ip

3.3962264150943398